import { RATONIX_API_BASE_URL, RATONIX_API_KEY } from "./config";
import type { RatonixRequest, RatonixSuggestion, Tone } from "./types";

type ApiSuggestionResponse = Partial<RatonixSuggestion>;

export class RatonixClient {
  constructor(
    private readonly endpoint = RATONIX_API_BASE_URL,
    private readonly apiKey = RATONIX_API_KEY,
  ) {}

  async rewrite(request: RatonixRequest): Promise<RatonixSuggestion> {
    if (this.endpoint) {
      try {
        const response = await this.post<ApiSuggestionResponse>("/rewrite", request);
        if (response.text) {
          return {
            text: response.text,
            rationale: response.rationale ?? "Generated by Ratonix.",
            source: "api",
          };
        }
      } catch (error) {
        console.warn("Ratonix rewrite API unavailable; using local tone guidance.", error);
      }
    }

    return localRewrite(request);
  }

  async draftReply(request: RatonixRequest): Promise<RatonixSuggestion> {
    if (this.endpoint) {
      try {
        const response = await this.post<ApiSuggestionResponse>("/draft-reply", request);
        if (response.text) {
          return {
            text: response.text,
            rationale: response.rationale ?? "Generated by Ratonix.",
            source: "api",
          };
        }
      } catch (error) {
        console.warn("Ratonix reply API unavailable; using local draft guidance.", error);
      }
    }

    return localDraftReply(request);
  }

  private async post<T>(path: string, body: unknown): Promise<T> {
    if (!this.endpoint) {
      throw new Error("Ratonix API endpoint is not configured.");
    }

    const response = await fetch(`${this.endpoint}${path}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(this.apiKey ? { Authorization: `Bearer ${this.apiKey}` } : {}),
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      throw new Error(`Ratonix API returned ${response.status}`);
    }

    return (await response.json()) as T;
  }
}

function localRewrite(request: RatonixRequest): RatonixSuggestion {
  const normalized = normalizeWhitespace(request.message.bodyText);
  const relationshipHint = relationshipSummary(request);
  const styleHint = request.memory.examples.length
    ? ` It uses ${request.memory.examples.length} local style example(s) for guidance.`
    : "";
  const rewritten = applyTone(normalized, request.tone);

  return {
    text: rewritten,
    rationale: `Local ${request.tone} rewrite${relationshipHint}.${styleHint} Connect a Ratonix API endpoint for adaptive AI output.`,
    source: "local",
  };
}

function localDraftReply(request: RatonixRequest): RatonixSuggestion {
  const subject = request.message.subject ? request.message.subject.replace(/^re:\s*/i, "") : "your message";
  const relationshipLine = relationshipSummary(request)
    ? `I kept your saved relationship context in mind.`
    : "I kept the sender's context in mind.";
  const styleLine = request.memory.examples.length
    ? `I also followed your saved communication style examples.`
    : "You can personalize this before sending.";
  const body = normalizeWhitespace(request.message.bodyText);
  const summary = body.length > 220 ? `${body.slice(0, 220).trim()}...` : body;
  const toneIntro = toneLeadIn(request.tone);

  return {
    text: `${toneIntro}\n\nThanks for reaching out about "${subject}". ${relationshipLine}\n\n${summary ? `On your note: ${summary}\n\n` : ""}${styleLine}\n\nBest,`,
    rationale: `Local ${request.tone} reply draft. Connect a Ratonix API endpoint for adaptive AI drafting.`,
    source: "local",
  };
}

function applyTone(text: string, tone: Tone): string {
  const trimmed = text.replace(/[.!?\s]*$/, "");

  if (!trimmed) {
    return "";
  }

  switch (tone) {
    case "softer":
      return `I appreciate you taking a look at this. ${trimmed}. Please let me know what you think when you have a chance.`;
    case "firmer":
      return `${trimmed}. Please prioritize this and confirm the next step.`;
    case "balanced":
    default:
      return `${trimmed}. Let me know if you have any questions.`;
  }
}

function toneLeadIn(tone: Tone): string {
  switch (tone) {
    case "softer":
      return "Hi, I appreciate the update.";
    case "firmer":
      return "Hi, thanks for the note. Here is the next step I recommend.";
    case "balanced":
    default:
      return "Hi, thanks for reaching out.";
  }
}

function relationshipSummary(request: RatonixRequest): string {
  const addresses = [request.message.from, ...(request.message.to ?? [])].filter(Boolean) as string[];
  const known = addresses
    .map((address) => request.memory.relationships[address.toLowerCase()])
    .filter(Boolean);

  return known.length ? ` with ${known.length} saved relationship profile(s)` : "";
}

function normalizeWhitespace(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}
